name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.
        Example: I'm always frustrated when [...] or I need to [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: |
        A clear and concise description of what you want to happen.
        If possible, include code examples or pseudo-code.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        What are the other ways to solve this problem?
        Why do you think your proposed solution is better?
    validations:
      required: false

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you suggesting?
      options:
        - New Technical Indicator
        - Performance Optimization
        - API Enhancement
        - Documentation Improvement
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Just an idea)
      default: 2
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe how you or others would use this feature.
      placeholder: |
        Example usage scenarios:
        1. When analyzing [...], I would use this feature to [...]
        2. This would help traders who need to [...]
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If you have any ideas about how to implement this feature, please share them.
      placeholder: |
        Technical details, algorithm suggestions, or references to similar implementations.
        Feel free to include links to papers, articles, or other resources.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I'm willing to help test this feature
        - label: I'm willing to help document this feature
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        - Screenshots or mockups
        - Links to similar features in other projects
        - Additional background information
    validations:
      required: false
