name: Question
description: Ask a question about usage, documentation, or development
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in kand! Before submitting a question, please:
        1. Check the [Documentation](https://github.com/qntx/kand/wiki)
        2. Search [existing issues](https://github.com/qntx/kand/issues)
        3. Look through [closed issues](https://github.com/qntx/kand/issues?q=is%3Aissue+is%3Aclosed)

  - type: dropdown
    id: question_type
    attributes:
      label: Question Type
      description: What area is your question about?
      options:
        - API Usage
        - Installation/Setup
        - Technical Indicators
        - Performance
        - Documentation
        - Development
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: |
        Provide a clear and concise description of your question.
        Include any relevant context that might help us answer better.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve? This helps us provide a more helpful answer.
      placeholder: |
        Example:
        - I'm building a trading system that needs to...
        - I'm trying to analyze market data for...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: If applicable, provide code that demonstrates your question.
      placeholder: |
        ```python
        import kand
        # Your code here
        ```
      render: python
    validations:
      required: false

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using?
      placeholder: "e.g. Python 3.8.10"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of kand are you using?
      placeholder: "e.g. 0.0.8"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - Windows
        - macOS
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have searched the documentation and existing issues
          required: true
        - label: I have included all relevant information needed to answer my question
          required: true
        - label: I have provided code examples (if applicable)
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other context or screenshots that might help us answer your question?
      placeholder: |
        - Screenshots of your setup or output
        - Error messages you're seeing (if any)
        - Links to related documentation or resources
    validations:
      required: false
