blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.rs/kand/latest/kand/
    about: Please consult the documentation before creating an issue.
  - name: Discussion
    url: https://github.com/orgs/rust-ta/discussions
    about: Join our community to ask questions and collaborate.
