name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, aarch64]
        exclude:
          - os: windows-latest
            arch: aarch64

    runs-on: ${{ matrix.os }}

    steps:
    # Checkout repository
    - uses: actions/checkout@v4

    # Setup Rust environment
    - name: Set up Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        cache: false

    # Build the project
    - name: Build project
      run: cargo build --verbose

    # Run test suite
    - name: Run tests
      run: cargo test --all-features --verbose

    # Run static code analysis with Clippy
    - name: Run Clippy
      run: cargo clippy --all-features --verbose -- -D warnings

    # Check code formatting
    - name: Run rustfmt
      run: cargo fmt -- --check
